version: "3"

services:
  api:
    container_name: crypto_x_action_api
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    ports:
      - "4000:4000"
      - "4001:4001"
    environment:
      HTTP_PORT: 4000
      APP_GETAWAY_PORT: 4001
      NODE_ENV: development
      DB_NAME: main
    env_file:
      - ./server/.env
      - ./mongo/.mongo.env
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_healthy
    links:
      - database:database
      - redis:redis
    volumes:
      - ./server:/home/app/x_server
      - ./server/.env:/home/app/x_server/.env
      - ./server/node_modules:/home/app/x_server/node_modules
    tty: true
    restart: "always"
    entrypoint: /bin/bash
    command: -s

  database:
    image: mongo:4.4
    container_name: crypto_x_action_database
    hostname: crypto_x_action_database
    env_file:
      - ./mongo/.mongo.env
    ports:
      - "27018:27017"
    volumes:
      - ./mongo/db:/data/db:rw
    #      - ./mongo/scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    tty: true
    restart: "always"
    entrypoint: [
      "/usr/bin/mongod",
      "--bind_ip_all",
      "--replSet", "rs0",
      "--journal",
      "--dbpath", "/data/db",
      "--setParameter", "transactionLifetimeLimitSeconds=5"
    ]

  database-setup:
    image: mongo:4.4
    container_name: crypto_x_action_database_setup
    env_file:
      - ./mongo/.mongo.env
    volumes:
      - ./mongo/scripts:/scripts
    links:
      - database:database
    depends_on:
      - database
    restart: "on-failure"
    entrypoint: [ "/scripts/setup-rs.sh" ]

  redis:
    image: redis:7.0.10-alpine
    container_name: crypto_x_action_redis
    ports:
      - "6373:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    tty: true
    restart: "always"
    command: ["redis-server", "--appendonly", "yes"] # start redis in persistent storage mode

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: crypto_x_action_redis_commander
    depends_on:
      - redis
    env_file:
      - ./server/.env
    ports:
      - "8082:8081"
    tty: true
    restart: "always"

volumes:
  redis-data: