FROM node:18-bullseye

ENV HOME_DIR /home/app
ENV API_DIR $HOME_DIR/x_server
ENV CLI_PATH ./dist/cli.js

ENV TZ=Europe/Kiev
ENV NODE_OPTIONS=--max_old_space_size=2548

#RUN apt-get update -y && \
#    apt-get install -yq tzdata && \
#    ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && \
#    dpkg-reconfigure -f noninteractive tzdata

WORKDIR $API_DIR

COPY ./server/package*.json ./
RUN npm install

COPY ./server $API_DIR

RUN npm run build

EXPOSE $PORT

CMD ["npm", "run" ,"start:prod"]
